### PR TITLE
grouped boxplot

### PR DESCRIPTION
**Pull request by wangjiawen2013**
It's tricky to implement grouped boxplot as we need to adjust the postions and width of the boxes to optimize the visualization layout without the prior knowledge on the group numbers and boxes numbers in each group. Here two helper function was defined to help users adjust the layout automatically.

### CODE REVIEW

**Comment by wangjiawen2013** [comment]
The test_boxplot6 was passed in my system, maybe if failed because the git cache.

**Comment by cpmech** [comment]
Hi, thanks for the PR. As far as I can see, the PR adds two functions named `adjust_positions_and_width_...`. They are a specific use of Boxplot and are best left out for the users to implement if they need such a feature.

**Comment by cpmech** [comment]
Thanks again for the improvement. Nonetheless, this is too specific. I would rather have `ploppy` deliver only "foundation" structures (as Matplotlib) for the users to create their own applications.

**Comment by wangjiawen2013** [comment]
I moved the two functions to the boxplot structure, and now they are associated functions. Grouped boxplot is used widely, but it's very hard to adjust the layout for the users, especially the users that are not familiar with matplotlib. In fact, they usually seaborn and plotnine instead. For matplotlib users, this can save a lot of time.

**Comment by cpmech** [comment]
Thanks, but I still want `plotpy` to contain only essential functionality.

**Comment by wangjiawen2013** [comment]
Can I add the two functions to the documentation ?

**Comment by cpmech** [comment]
I'd rather not have the functions in the documentation because, in the future, people may come to me asking for help, and I may not be able to help. Also, everything in the documentation needs to be fully tested, and thus, we would need "real" Rust code in there---i.e., it would be the same as having the code directly in the repository. I suggest you create a GitHub Gist to advertise such code snippets.

**Comment by wangjiawen2013** [comment]
I'll open an issue and elaborate on how to plot grouped boxplot. I am worried that I'll forget the functions. It's takes some time to develop the layout algorithm.

**Comment by cpmech** [comment]
You may also create a GitHub Gist (see https://gist.github.com/) on your account to save "code that you don't want to forget" ;-)

**Comment by wangjiawen2013** [comment]
I don't know about GitHub Gist, I'll try to use it later.

**Pull request closed without merging**
